---
title: "CyGenPlots"
output: 
  html_document: 
    keep_md: yes
---
```{r libraries}
library(tidyverse)
library(janitor)
```

```{r load-data}
df_from_anvi = read_tsv("/Users/hehouts/projects/cold-tolerant-cyanos/outputs/gene-hits/gene_hit_matrix_output.tsv")
df_from_anvi = df_from_anvi %>% rename(genome=genome_or_bin)
colnames(df_from_anvi)
```

```{r}
df_from_anvi_melt = reshape2::melt(df_from_anvi) %>% rename("gene"="variable") %>% rename("gene_count"="value")
colnames(df_from_anvi_melt)
```



```{r plot-libraries}
#install.packages("viridis")
library(viridis)
```

```{r}


### these are not needed, because they are notw loaded in in the same .Rmd that they are used in 
#df = read_tsv("/Users/hehouts/projects/cold-tolerant-cyanos/outputs/gene-hits/gene_hit_matrix_output.tsv")
#df_og = read_tsv("/Users/kaylahmarcello/Desktop/sumner_lab/cold-tolerant-cyanos/outputs/gene-hits/gene_hit_matrix_output.tsv")
#df_og = read_tsv("/Users/hehouts/projects/cold-tolerant-cyanos/outputs/gene-hits/gene_hit_matrix_output.tsv")
#df_og = df_og%>% rename("Genome"="genome_or_bin")




df_og = df_from_anvi


file_basename_to_orgname_df = read_csv("genome-filename-to-basename.csv")
file_basename_to_orgname_df = clean_names(file_basename_to_orgname_df)
```

```{r}
print("file_basename_to_orgname_df")
colnames(file_basename_to_orgname_df)

print("df_og")
colnames(df_og)
```

```{r}
#file_basename_to_orgname_df = file_basename_to_orgname_df %>%
#  select(`Base Name`, `Organism Name`, `Temp`) %>%
#  rename(Name = `Organism Name`)

df = left_join(df_og,file_basename_to_orgname_df, by = c("genome" = "base_name"))
colnames(df)
df = df %>% select(!genome) %>% relocate(organism_name)
#%>% rename (genome = "name")
colnames(df)
```
```{r}
df_melt = reshape2::melt(df) %>% rename("gene"="variable") %>% rename("gene_count"="value") %>%  mutate(gene_count = as.factor(gene_count))
colnames(df_melt)

```





```{r}
#full heatmap

  full_heatmap <- df_melt %>%
  ggplot(aes(y=gene, x=organism_name))+
  geom_tile(aes(fill= gene_count, color="white"))+
  scale_fill_viridis(discrete=TRUE, direction = -1)+
  theme(legend.position = "right",
        text = element_text(size=4),
        axis.text.x = element_text(angle = 45, hjust=1))#+
#  coord_fixed()+ #maintains aspect ratio so 1 unit on x is 1 unit on y
#  labs(title = "Gene Count",x = "Genome", y = "Gene")

#ggsave("gene_count_heatmap.png", plot = full_heatmap, dpi = 200)
 

full_heatmap 
```

