---
title: "graveyard"
output: html_document
---




this chunk is mostly obsolete now that we have a `gene_hit_matrix_output.tsv`:
```{used old matrix, r}

#Needed files: "file_names.txt", "sub_gene_counts.csv",

  #!!! After installing, comment that line out bc it doesnt need to be run over and over. In theory, just once. 
#install.packages("tidyverse")
library(tidyverse)
df = read_csv("sub_gene_counts.csv")

df_relocated = df %>% relocate(Organism) %>% relocate(RefSeq_acc, .after = yfiA)
df_trim = df_relocated %>% select(c(1:22))
df_melt = reshape2::melt(df_trim)

heatmap1 = df_melt %>% 
  ggplot(aes(y=Organism, x=variable))+
    geom_tile(aes(fill= value), color="grey")+
    scale_fill_gradient(low="white", high="blue") +
    theme(axis.text.x = element_text(angle = 45, hjust=1))+
      #theme(legend.position = "right")+
    coord_fixed()+ #maintains aspect ratio so 1 unit on x is 1 unit on y
    labs(title = "Gene Count",x = "gene", y = "Genome")
ggsave("heatmap1.png", plot = heatmap1)
```


this is an old, ugly(sorry) heatmap:
```{r}
df_full_melt = reshape2::melt(df_from_anvi) %>% rename("Genome"="genome_or_bin") %>% rename("Gene"="variable") %>% rename("Gene_Count"="value")


full_heatmap <- df_full_melt %>% 
  ggplot(aes(x=Genome, y=Gene))+
   geom_tile(aes(fill= Gene_Count), color="grey")+
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 45, hjust=1))+
  coord_fixed()+ #maintains aspect ratio so 1 unit on x is 1 unit on y
    labs(title = "Gene Count",x = "Genome", y = "Gene")
ggsave("full_heatmap.png", plot = full_heatmap)
full_heatmap

```


these are not needed, because they are notw loaded in in the same .Rmd that they are used in 
```{r}
#df = read_tsv("/Users/hehouts/projects/cold-tolerant-cyanos/outputs/gene-hits/gene_hit_matrix_output.tsv")
#df_og = read_tsv("/Users/kaylahmarcello/Desktop/sumner_lab/cold-tolerant-cyanos/outputs/gene-hits/gene_hit_matrix_output.tsv")
#df_og = read_tsv("/Users/hehouts/projects/cold-tolerant-cyanos/outputs/gene-hits/gene_hit_matrix_output.tsv")
```